### PR TITLE
Set handler for views & fixed names.

### LINKED ISSUE #87: Add views integration.
Pass active Menu Link Content Entity to views using context
Could be some other cases.

### PR DESCRIPTION
**Pull request by ozin7**
Still need to add plugin for context

resolve #87

### CODE REVIEW

File: src/Plugin/views/argument_default/MenuLinkContentId.php [hunk 1]
```diff
@@ -0,0 +1,154 @@
...
+   * @return \Drupal\Core\Entity\EntityInterface[]
+   */
+  public function getMenus() {
+    $menus = $this->entityTypeManager
+      ->getStorage('menu')
+      ->loadMultiple();
+
+    return $menus;
+  }
+}
```
Comment (iVegas) [inline src/Plugin/views/argument_default/MenuLinkContentId.php]: New line before }

File: src/Plugin/views/argument_default/MenuLinkContentId.php [hunk 2]
```diff
@@ -0,0 +1,154 @@
...
+   */
+  public function calculateDependencies() {
+    $dependencies = parent::calculateDependencies();
+    return $dependencies;
+  }
+
+  /**
+   * Get menus.
+   * @return \Drupal\Core\Entity\EntityInterface[]
+   */
```
Comment (iVegas) [inline src/Plugin/views/argument_default/MenuLinkContentId.php]: Add description for @return

File: src/Plugin/views/argument_default/MenuLinkContentId.php [hunk 3]
```diff
@@ -0,0 +1,154 @@
...
+   * {@inheritdoc}
+   */
+  public function calculateDependencies() {
+    $dependencies = parent::calculateDependencies();
+    return $dependencies;
+  }
+
+  /**
+   * Get menus.
+   * @return \Drupal\Core\Entity\EntityInterface[]
```
Comment (iVegas) [inline src/Plugin/views/argument_default/MenuLinkContentId.php]: New line before `@return`

File: src/Plugin/views/argument_default/MenuLinkContentId.php [hunk 4]
```diff
@@ -0,0 +1,154 @@
...
+      $container->get('menu.link_tree')
+    );
+  }
+
+  /**
+   * {@inheritdoc}
+   */
+  public function buildOptionsForm(&$form, FormStateInterface $form_state) {
+    $options = [];
+    /** @var  \Drupal'system\Entity\Menu[] $menus */
```
Comment (iVegas) [inline src/Plugin/views/argument_default/MenuLinkContentId.php]: Replace double spaces

File: src/Plugin/views/argument_default/MenuLinkContentId.php [hunk 5]
```diff
@@ -0,0 +1,154 @@
...
+   * @var \Drupal\Core\Entity\EntityTypeManagerInterface
+   */
+  protected $entityTypeManager;
+
+  /**
+   * Menu tree.
+   * @var \Drupal\Core\Menu\MenuLinkTreeInterface
+   */
+  protected $menuTree;
+  /**
```
Comment (iVegas) [inline src/Plugin/views/argument_default/MenuLinkContentId.php]: New line before function

File: src/Plugin/views/argument_default/MenuLinkContentId.php [hunk 6]
```diff
@@ -0,0 +1,154 @@
...
+
+  /**
+   * Entity type manager.
+   * @var \Drupal\Core\Entity\EntityTypeManagerInterface
+   */
+  protected $entityTypeManager;
+
+  /**
+   * Menu tree.
+   * @var \Drupal\Core\Menu\MenuLinkTreeInterface
```
Comment (iVegas) [inline src/Plugin/views/argument_default/MenuLinkContentId.php]: New line before `@var`

File: src/Plugin/views/argument_default/MenuLinkContentId.php [hunk 7]
```diff
@@ -0,0 +1,154 @@
...
+  /**
+   * The route match.
+   *
+   * @var \Drupal\Core\Routing\RouteMatchInterface
+   */
+  protected $routeMatch;
+
+  /**
+   * Entity type manager.
+   * @var \Drupal\Core\Entity\EntityTypeManagerInterface
```
Comment (iVegas) [inline src/Plugin/views/argument_default/MenuLinkContentId.php]: New line before `@var`

**Comment by iVegas** [comment]
@ozin7 Is that's all in this PR?

File: src/Plugin/views/argument_default/MenuLinkContentId.php [hunk 8]
```diff
@@ -0,0 +1,205 @@
...
+   * @param string $current_path
+   *   Current path.
+   *
+   * @return \Drupal\Core\Menu\MenuLinkTreeElement|null
+   *   Active menu item.
+   */
+  public function getActiveMenuItem(array $menu_level, $current_path) {
+    $active_item = NULL;
+    /** @var \Drupal\Core\Menu\MenuLinkTreeElement[] $menu_level */
+    foreach ($menu_level as $menu_item_key => $menu_item) {
```
Comment (iVegas) [inline src/Plugin/views/argument_default/MenuLinkContentId.php]: Remove $menu_item_key as unused variable

File: src/Plugin/views/argument_default/MenuLinkContentId.php [hunk 9]
```diff
@@ -0,0 +1,205 @@
...
+   * @param array $configuration
+   *   A configuration array containing information about the plugin instance.
+   * @param string $plugin_id
+   *   The plugin_id for the plugin instance.
+   * @param mixed $plugin_definition
+   *   The plugin implementation definition.
+   * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
+   *   The route match.
+   * @param \Drupal\Core\Entity\EntityTypeManagerInterface $entity_type_manager
+   *   The entity type manager..
```
Comment (iVegas) [inline src/Plugin/views/argument_default/MenuLinkContentId.php]: Doubling `..`
